version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: costchef_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb+srv://Buck:Trevogavjope@cluster0.ruk1ewc.mongodb.net/costchef?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: costchef_super_secret_jwt_key_2024
    ports:
      - "3001:3001"
    networks:
      - costchef_network
    healthcheck:
      test: [ "CMD", "node", "healthcheck.js" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: costchef_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - costchef_network

networks:
  costchef_network:
    driver: bridge
